version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: lendsoftware
      POSTGRES_USER: lend_user_software
      POSTGRES_PASSWORD: "YfC%L&5GtDM2LhoEPrcU"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet
    ports:
      - "5432:5432"

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: lendsoftware
      DB_USER: lend_user_software
      DB_PASSWORD: "YfC%L&5GtDM2LhoEPrcU"
      DJANGO_SETTINGS_MODULE: backend.settings
    depends_on:
      - db
    networks:
      - webnet
    labels:
      # HTTPS
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.sportweber-schnaittach.de`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

      # HTTP -> HTTPS Redirect
      - "traefik.http.routers.backend-http.rule=Host(`backend.sportweber-schnaittach.de`)"
      - "traefik.http.routers.backend-http.entrypoints=web"
      - "traefik.http.routers.backend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=michael.reinert@wesolve-it.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - webnet

volumes:
  postgres_data:
  letsencrypt:

networks:
  webnet:
    external: true
