# Generated by Django 3.1.1 on 2025-02-25 15:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DrivingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('label', models.CharField(max_length=30)),
                ('pricePerDay', models.DecimalField(decimal_places=2, max_digits=8)),
                ('serialNumber', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('bookingDate', models.DateField(default=django.utils.timezone.now)),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phoneNumber', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=70, null=True)),
                ('local', models.CharField(max_length=70, null=True)),
                ('note', models.TextField(max_length=300, null=True)),
                ('is_invoice_downloaded', models.BooleanField(default=False)),
                ('size', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='object', to='lend_app.size')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lend_app.category')),
                ('driving_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lend_app.drivingprofile')),
                ('sizes', models.ManyToManyField(to='lend_app.Size')),
            ],
        ),
    ]
