# Generated by Django 3.1.1 on 2025-10-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='is_invoice_downloaded',
            new_name='invoice_downloaded',
        ),
    ]
