# Generated by Django 3.1.1 on 2023-11-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('label', models.CharField(max_length=30)),
                ('pricePerDay', models.DecimalField(decimal_places=3, max_digits=8)),
                ('serialNumber', models.CharField(max_length=80)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lend_app.article')),
                ('booked_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lend_app.booked')),
            ],
        ),
        migrations.AddField(
            model_name='booked',
            name='size_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lend_app.size'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lend_app.category'),
        ),
    ]
