# Generated by Django 3.1.1 on 2023-11-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lend_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='size_id',
        ),
        migrations.RemoveField(
            model_name='size',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='size',
            name='booked_id',
        ),
        migrations.AddField(
            model_name='booked',
            name='size',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='object', to='lend_app.size'),
        ),
        migrations.AddField(
            model_name='size',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='object', to='lend_app.article'),
        ),
        migrations.AddField(
            model_name='size',
            name='booked',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='lend_app.booked'),
        ),
    ]
