# Generated by Django 3.1.1 on 2023-11-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lend_app', '0002_auto_20231110_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='booked',
        ),
    ]
