# Generated by Django 3.1.1 on 2023-11-15 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend_app', '0004_auto_20231110_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='bookingDate',
            field=models.DateField(default=datetime.date(2023, 11, 15)),
        ),
        migrations.AddField(
            model_name='booked',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booked',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booked',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booked',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booked',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booked',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
