# Generated by Django 3.1.1 on 2023-11-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend_app', '0005_auto_20231115_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='sizes',
            field=models.ManyToManyField(to='lend_app.Size'),
        ),
    ]
